# Generated by Django 3.2.3 on 2022-08-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'Placed'), (2, 'Packed'), (3, 'Dispatched'), (4, 'Delivered')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.customer')),
            ],
        ),
    ]
